use std::{
    fs,
    path::{Path, PathBuf},
};

use stratum_apps::key_utils::{Secp256k1PublicKey, Secp256k1SecretKey};
use tracing::{debug, info, warn};

use crate::error::KeyManagementError;

//The default datadir path
pub const BRAIDPOOL_DIR: &str = ".braidpool";
pub const AUTHORITY_KEY_FILE: &str = "authority.key";

pub fn get_braidpool_dir() -> Result<PathBuf, KeyManagementError> {
    dirs::home_dir()
        .map(|home| home.join(BRAIDPOOL_DIR))
        .ok_or(KeyManagementError::NoHomeDirectory)
}

pub fn get_authority_key_path() -> Result<PathBuf, KeyManagementError> {
    get_braidpool_dir().map(|dir| dir.join(AUTHORITY_KEY_FILE))
}

pub fn load_or_generate_authority_keypair(
) -> Result<(Secp256k1PublicKey, Secp256k1SecretKey), KeyManagementError> {
    let key_path = get_authority_key_path()?;
    load_or_generate_keypair_at_path(&key_path)
}

/// Loads an existing authority keypair from the specified path or generates a new one.
//
/// A tuple of `(Secp256k1PublicKey, Secp256k1SecretKey)` for use in Noise handshakes.
pub fn load_or_generate_keypair_at_path(
    key_path: &Path,
) -> Result<(Secp256k1PublicKey, Secp256k1SecretKey), KeyManagementError> {
    match fs::read(key_path) {
        Ok(bytes) => {
            debug!(path = %key_path.display(), "Loading authority keypair from disk");
            load_keypair_from_bytes(&bytes)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            debug!(path = %key_path.display(), "Generating new authority keypair");
            generate_and_store_keypair(key_path)
        }
        Err(e) => {
            warn!(error = %e, path = %key_path.display(), "Failed to read key file");
            Err(KeyManagementError::ReadKey(e))
        }
    }
}

//Loading the authority key generated by upstream pool
pub fn load_authority_public_key() -> Result<Secp256k1PublicKey, KeyManagementError> {
    let key_path = get_authority_key_path()?;
    load_authority_public_key_from_path(&key_path)
}

/// Loads the authority public key from a specified path.
pub fn load_authority_public_key_from_path(
    key_path: &Path,
) -> Result<Secp256k1PublicKey, KeyManagementError> {
    match fs::read(key_path) {
        Ok(bytes) => {
            debug!(path = %key_path.display(), "Loading authority public key from disk");
            let (public, _secret) = load_keypair_from_bytes(&bytes)?;
            Ok(public)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            warn!(path = %key_path.display(), "Authority key file not found");
            Err(KeyManagementError::KeyNotFound(key_path.to_path_buf()))
        }
        Err(e) => {
            warn!(error = %e, path = %key_path.display(), "Failed to read key file");
            Err(KeyManagementError::ReadKey(e))
        }
    }
}

/// Loads a keypair from raw bytes which is the authority key being used for `NoiseHandshake` and owned inside the `UncommittedMetadata` of Bead
/// produced by the correpsonding miner
fn load_keypair_from_bytes(
    bytes: &[u8],
) -> Result<(Secp256k1PublicKey, Secp256k1SecretKey), KeyManagementError> {
    if bytes.len() != 32 {
        return Err(KeyManagementError::ParseKey(format!(
            "Invalid key length: expected 32 bytes, got {}",
            bytes.len()
        )));
    }
    // Convert bytes to base58check string and parse
    let encoded = bs58::encode(bytes).with_check().into_string();
    //Parsing the bytes
    let secret: Secp256k1SecretKey = encoded.parse().map_err(|e| {
        KeyManagementError::ParseKey(format!("Failed to parse secret key: {:?}", e))
    })?;
    let public = Secp256k1PublicKey::from(secret);
    //Authority key pair
    Ok((public, secret))
}

/// Generates a new secp256k1 keypair and stores it at the specified path.
fn generate_and_store_keypair(
    key_path: &Path,
) -> Result<(Secp256k1PublicKey, Secp256k1SecretKey), KeyManagementError> {
    use rand::RngCore;

    // Create parent directory if it doesn't exist
    if let Some(parent) = key_path.parent() {
        fs::create_dir_all(parent).map_err(KeyManagementError::DirectoryCreation)?;
    }

    // Generate a valid secret key
    let mut rng = rand::thread_rng();
    let mut secret_bytes = [0u8; 32];
    //Looping is only for the purpose if we are not able to produce a valid secret key
    // This is extremely rare (probability < 2^-127) but we handle it for correctness
    loop {
        rng.fill_bytes(&mut secret_bytes);

        // Encoding to base58 and storing the bytes to braidpool datadir
        let encoded = bs58::encode(&secret_bytes).with_check().into_string();
        if let Ok(secret) = encoded.parse::<Secp256k1SecretKey>() {
            // Valid secret key found, store it
            fs::write(key_path, &secret_bytes).map_err(KeyManagementError::WriteKey)?;

            // Set restrictive permissions on Unix systems
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let mut perms = fs::metadata(key_path)
                    .map_err(KeyManagementError::Permissions)?
                    .permissions();
                perms.set_mode(0o400);
                fs::set_permissions(key_path, perms).map_err(KeyManagementError::Permissions)?;
            }

            info!(path = %key_path.display(), "Authority keypair generated and stored");

            let public = Secp256k1PublicKey::from(secret);
            return Ok((public, secret));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_generate_and_load_keypair() {
        let temp_dir = tempdir().unwrap();
        let key_path = temp_dir.path().join("test_authority.key");

        let (pub1, sec1) = load_or_generate_keypair_at_path(&key_path).unwrap();

        assert!(key_path.exists());

        let (pub2, sec2) = load_or_generate_keypair_at_path(&key_path).unwrap();

        assert_eq!(pub1.into_bytes(), pub2.into_bytes());
        assert_eq!(sec1.into_bytes(), sec2.into_bytes());
    }

    #[test]
    fn test_keypair_consistency() {
        let temp_dir = tempdir().unwrap();
        let key_path = temp_dir.path().join("test_authority.key");

        let (public, secret) = load_or_generate_keypair_at_path(&key_path).unwrap();

        let derived_public = Secp256k1PublicKey::from(secret);
        assert_eq!(public.into_bytes(), derived_public.into_bytes());
    }

    #[test]
    fn test_invalid_key_length() {
        let invalid_bytes = vec![0u8; 16]; // Too short
        let result = load_keypair_from_bytes(&invalid_bytes);
        assert!(result.is_err());
    }

    #[test]
    fn test_key_not_found_error() {
        let temp_dir = tempdir().unwrap();
        let key_path = temp_dir.path().join("nonexistent.key");

        let result = load_authority_public_key_from_path(&key_path);
        assert!(matches!(result, Err(KeyManagementError::KeyNotFound(_))));
    }

    #[test]
    fn test_load_public_key_only() {
        let temp_dir = tempdir().unwrap();
        let key_path = temp_dir.path().join("test_authority.key");

        let (expected_public, _) = load_or_generate_keypair_at_path(&key_path).unwrap();

        let loaded_public = load_authority_public_key_from_path(&key_path).unwrap();

        assert_eq!(expected_public.into_bytes(), loaded_public.into_bytes());
    }
}
